import {
	custom,
	defineModel,
	enums,
	instant,
	integer,
	numeric,
	text,
	uuid
} from '@norbital-ai/bolt/authoring';

export default defineModel(
	{
		employment_id: uuid().notNull(),
		leave_catalogue_id: uuid().notNull(),
		leave_year: integer().notNull(),
		starts_on: instant({ precision: 'day' }).notNull(),
		ends_on: instant({ precision: 'day' }).notNull(),
		status: enums(['OPEN', 'CLOSED']).notNull().default('OPEN'),
		/** The band the row was generated with; later catalogue edits post `ADJUSTMENT` lines instead. */
		entitlement_days: numeric().notNull(),
		accrual_kind: enums(['UPFRONT', 'MONTHLY', 'UNLIMITED']).notNull(),
		/** Copied from the type at creation, sealed: what the year end does with the unused balance. */
		settlement: custom('leave_settlement').notNull(),
		/** Copied from the type at creation, sealed: what the balance does when the employment ends. */
		exit_settlement: custom('leave_exit_settlement').notNull(),
		leave_code: text({ search: true }).notNull(),
		leave_name: text({ search: true }).notNull()
	},
	{
		description:
			'One employment, one leave, one leave year, generated by the reconciler and never seeded. The balance is the sum of its append-only entries.',
		recordLabel: 'leave_name',
		icon: 'lucide:wallet-cards',
		indexes: [
			{ columns: ['employment_id', 'leave_catalogue_id', 'leave_year'], unique: true },
			{ columns: ['starts_on', 'ends_on'] }
		]
	}
);
