<script lang="ts">
	/**
	 * One consumed attendance/leave record under one payslip.
	 *
	 * `payslip_id` names the owner and `source` is the one discriminated reference handle. Its
	 * physical UUID arms are generated by Bolt and never appear in this form.
	 */
	import { client } from '../../lib/workspace-client.js';
	import { useI18n } from '@norbital-ai/ui/i18n';
	import type { TenantI18nKeys } from '$bolt/i18n-keys';
	import type { RepresentationProps } from './$types.js';
	import { CollectionForm } from '@norbital-ai/ui/collection-form';
	import { Column, Grid } from '@norbital-ai/ui/layout';
	import { RelationshipRenderer } from '@norbital-ai/ui/data-renderer/relationship';

	let { record, close }: RepresentationProps = $props();
	const { t } = useI18n<TenantI18nKeys>();
</script>

<CollectionForm
	{client}
	collection="payslip_sources"
	defaultValues={record ?? undefined}
	onAfterSubmit={record ? undefined : close}
>
	{#snippet children({ Field })}
		<Grid gap="md" minimum="panel">
			<Field
				name="payslip_id"
				label={t('component.payslip')}
				renderer={RelationshipRenderer}
				rendererProps={{
					target: 'payslips',
					options: {
						label: (payslip) =>
							payslip.period != null && payslip.period !== '' ? String(payslip.period) : '—',
						orderBy: { period: 'desc' },
						limit: 500
					}
				}}
			/>
			<Field name="period" label={t('component.pay_period')} />
			<Column span="all"><Field name="source" label={t('component.source_record')} /></Column>
		</Grid>
	{/snippet}
</CollectionForm>
