import { Effect } from 'effect';
import type { Api as HookApi, AutomationApi } from '@norbital-ai/bolt/authoring';
import type { WorkspaceSchema } from '$bolt/types.js';

/**
 * Leave entitlements are generated by one service and written inline with the row that owns them.
 *
 * The arithmetic in `reconcile.ts` reads and writes through the authored `api.db` surface. Here it
 * runs against an in-memory context that was read once for a whole batch, and everything it wrote
 * is handed back as nested rows for the owning mutation: an employment nests its entitlements,
 * each nesting its ledger entries. Nothing here writes to the database. Ids are deterministic, so
 * an entitlement can be referenced by the entries that open it before anything exists, and a
 * leave request can name its entitlement by formula.
 *
 * Two readers share it. The employment's `before` hook plans one employment from the context its
 * batch read, with the row being written overlaid (`withPending`), and returns the plan nested
 * under the employment. The monthly reconciler plans a page of employments and writes each as one
 * root touch (`applyLeavePlan`).
 */

/** The leave service needs only the data surface; hooks and automations hand it theirs. */
export type LeaveApi = Readonly<{ readonly db: AutomationApi['db'] }>;
/** The reads alone, which a hook's api (its inputs untyped) and an automation's both provide. */
type LeaveReadApi = LeaveApi | Readonly<{ readonly db: HookApi<WorkspaceSchema, unknown>['db'] }>;
type Api = LeaveApi;
export type Row = Readonly<Record<string, unknown>> & { readonly id: string };
type Db = Api['db'];

const LIMIT = 5_000;

export {
	leaveEntitlementIdFor,
	leaveEntryIdFor,
	requestSourceKey,
	stableUuid
} from './identity.js';
import { leaveEntitlementIdFor, leaveEntryIdFor } from './identity.js';

export type LeaveContext = {
	readonly employments: Row[];
	readonly companies: Row[];
	/** Every version of every lineage the companies bind to; the reconciler picks per rule date. */
	readonly jurisdiction_settings: Row[];
	readonly employees: Row[];
	readonly employment_terms: Row[];
	readonly employee_children: Row[];
	readonly leave_catalogue: Row[];
	readonly leave_entitlements: Row[];
	readonly leave_entries: Row[];
	readonly leave_requests: Row[];
};

const chunks = <T>(items: ReadonlyArray<T>, size: number): T[][] => {
	const out: T[][] = [];
	for (let index = 0; index < items.length; index += size)
		out.push([...items.slice(index, index + size)]);
	return out;
};

const readAll = <T>(
	ids: ReadonlyArray<string>,
	read: (chunk: ReadonlyArray<string>) => Effect.Effect<ReadonlyArray<T>>
): Effect.Effect<T[]> =>
	Effect.map(
		Effect.forEach(chunks([...new Set(ids)], 200), (chunk) => read(chunk), { concurrency: 4 }),
		(pages) => {
			if (pages.some((page) => page.length >= LIMIT))
				throw new Error(
					'Leave context read hit its page ceiling; the batch is too large to plan safely.'
				);
			return pages.flat();
		}
	);

/**
 * Every row the arithmetic may ask for while reconciling these employments, read in bulk.
 *
 * Creates have no stored employment yet, so a hook names the companies and employees its batch
 * writes against (`companyIds`, `employeeIds`); the catalogue is read through the companies'
 * settings lineages, every version of each, and the row being written is overlaid afterwards
 * with `withPending`. With `asOf` only the leave years
 * around that date are read, which is the monthly walk's bound; a hook plans a few employments
 * from a date the fact states, so it omits `asOf` and reads their whole ledger.
 */
export const readLeaveContext = (
	api: LeaveReadApi,
	employmentIds: ReadonlyArray<string>,
	extra: {
		readonly companyIds?: ReadonlyArray<string>;
		readonly employeeIds?: ReadonlyArray<string>;
		/** The planning date; only the leave years around it are read, never the whole history. */
		readonly asOf?: string;
	}
) =>
	Effect.gen(function* () {
		// A leave year is labelled by the calendar year it starts in, so the previous, current and
		// next leave years of any company lie within two calendar years of the planning date.
		const yearFloor = extra.asOf === undefined ? undefined : Number(extra.asOf.slice(0, 4)) - 2;
		const db = api.db as unknown as Record<
			string,
			{ findMany: (input: Record<string, unknown>) => Effect.Effect<ReadonlyArray<Row>> }
		>;
		const many = (collection: string, where: Record<string, unknown>) =>
			db[collection]!.findMany({ where, limit: LIMIT });
		const employments = yield* readAll(employmentIds, (ids) =>
			many('employments', { id: { in: ids }, approval_id: { isNull: true } })
		);
		const companyIds = [
			...new Set([...employments.map((row) => String(row.company_id)), ...(extra.companyIds ?? [])])
		];
		const employeeIds = [
			...new Set([
				...employments.map((row) => String(row.employee_id)),
				...(extra.employeeIds ?? [])
			])
		];
		const presentIds = employments.map((row) => row.id);
		const companies = yield* readAll(companyIds, (ids) =>
			many('companies', { id: { in: ids }, approval_id: { isNull: true } })
		);
		const codes = [...new Set(companies.map((row) => String(row.settings_code)))];
		const versions = yield* readAll(codes, (chunk) =>
			many('jurisdiction_settings', { code: { in: chunk }, approval_id: { isNull: true } })
		);
		const versionIds = versions.map((row) => row.id);
		const [employees, terms, children, types, entitlements, requests] = yield* Effect.all(
			[
				readAll(employeeIds, (ids) => many('employees', { id: { in: ids } })),
				readAll(presentIds, (ids) =>
					many('employment_terms', { employment_id: { in: ids }, approval_id: { isNull: true } })
				),
				readAll(presentIds, (ids) =>
					many('employee_children', { employment_id: { in: ids }, approval_id: { isNull: true } })
				),
				readAll(versionIds, (ids) =>
					many('leave_catalogue', { settings_id: { in: ids }, approval_id: { isNull: true } })
				),
				readAll(presentIds, (ids) =>
					many('leave_entitlements', {
						employment_id: { in: ids },
						approval_id: { isNull: true },
						...(yearFloor === undefined ? {} : { leave_year: { gte: yearFloor } })
					})
				),
				readAll(presentIds, (ids) =>
					many('leave_requests', { employment_id: { in: ids }, approval_id: { isNull: true } })
				)
			],
			{ concurrency: 'unbounded' }
		);
		const entries = yield* readAll(
			entitlements.map((row) => row.id),
			(ids) =>
				many('leave_entries', { leave_entitlement_id: { in: ids }, approval_id: { isNull: true } })
		);
		return {
			employments: [...employments],
			companies: [...companies],
			jurisdiction_settings: [...versions],
			employees: [...employees],
			employment_terms: [...terms],
			employee_children: [...children],
			leave_catalogue: [...types],
			leave_entitlements: [...entitlements],
			leave_entries: [...entries],
			leave_requests: [...requests]
		} satisfies LeaveContext;
	});

/**
 * The context with one uncommitted row in it: the employment, term or child a hook is writing,
 * which the arithmetic must see as if it were stored. Every array is copied, so the planner built
 * over the result keeps its writes to itself and the batch's shared context stays as it was read.
 */
export const withPending = (
	context: LeaveContext,
	collection: keyof LeaveContext,
	row: Row
): LeaveContext => {
	const copy = Object.fromEntries(
		Object.entries(context).map(([name, rows]) => [name, [...rows]])
	) as { -readonly [K in keyof LeaveContext]: Row[] };
	copy[collection] = [...copy[collection].filter((stored) => stored.id !== row.id), row];
	return copy;
};

type Where = Readonly<Record<string, unknown>>;

/** The small `where` vocabulary the leave arithmetic uses, evaluated against a row in memory. */
const matches = (row: Row, where: Where | undefined): boolean => {
	if (where == null) return true;
	return Object.entries(where).every(([field, condition]) => {
		if (field === 'AND') return (condition as Where[]).every((part) => matches(row, part));
		if (field === 'OR') return (condition as Where[]).some((part) => matches(row, part));
		const value = row[field];
		const rule = condition as Readonly<Record<string, unknown>>;
		return Object.entries(rule).every(([operator, expected]) => {
			switch (operator) {
				case 'eq':
					return value === expected;
				case 'ne':
					return value !== expected;
				case 'in':
					return (expected as unknown[]).includes(value);
				case 'isNull':
					return expected ? value == null : value != null;
				case 'isNotNull':
					return expected ? value != null : value == null;
				case 'gt':
					return value != null && (value as string | number) > (expected as string | number);
				case 'gte':
					return value != null && (value as string | number) >= (expected as string | number);
				case 'lt':
					return value != null && (value as string | number) < (expected as string | number);
				case 'lte':
					return value != null && (value as string | number) <= (expected as string | number);
				default:
					throw new Error(`leave batch facade: unsupported where operator ${operator} on ${field}`);
			}
		});
	});
};

const select = (rows: ReadonlyArray<Row>, input: Record<string, unknown> | undefined): Row[] => {
	let out = rows.filter((row) => matches(row, input?.where as Where | undefined));
	const orderBy = input?.orderBy as Record<string, 'asc' | 'desc'> | undefined;
	if (orderBy != null) {
		const [[field, direction]] = Object.entries(orderBy);
		out = [...out].sort((left, right) => {
			const a = left[field] as string | number;
			const b = right[field] as string | number;
			return (a < b ? -1 : a > b ? 1 : 0) * (direction === 'desc' ? -1 : 1);
		});
	}
	const limit = input?.limit as number | undefined;
	return limit == null ? out : out.slice(0, limit);
};

/**
 * The arithmetic's api, backed by the context. Reads see every write made so far; writes are
 * kept in memory under deterministic ids and handed back as nested rows for the owning mutation.
 */
export const leavePlanner = (
	context: LeaveContext,
	pending: Api['db']['leave_requests']['findPending']
) => {
	const createdEntitlements = new Set<string>();
	const updatedEntitlements = new Map<string, Record<string, unknown>>();
	const createdEntries = new Set<string>();
	const reads = (collection: keyof LeaveContext) => ({
		findMany: (input?: Record<string, unknown>) =>
			Effect.succeed(select(context[collection], input)),
		findFirst: (input?: Record<string, unknown>) =>
			Effect.succeed(select(context[collection], { ...input, limit: 1 })[0] ?? null)
	});
	const mutateEntitlements = (rows: ReadonlyArray<Record<string, unknown>>) =>
		Effect.sync(() => {
			for (const values of rows) {
				const id =
					typeof values.id === 'string'
						? values.id
						: leaveEntitlementIdFor(values as Parameters<typeof leaveEntitlementIdFor>[0]);
				const existing = context.leave_entitlements.find((row) => row.id === id);
				if (existing != null) {
					Object.assign(existing, values, { id });
					if (!createdEntitlements.has(id))
						updatedEntitlements.set(id, { ...(updatedEntitlements.get(id) ?? {}), ...values, id });
				} else {
					context.leave_entitlements.push({ ...values, id, approval_id: null } as Row);
					createdEntitlements.add(id);
				}
			}
		});
	const mutateEntries = (rows: ReadonlyArray<Record<string, unknown>>) =>
		Effect.sync(() => {
			for (const values of rows) {
				const entry = values as { leave_entitlement_id: string; source_key: string };
				const id = typeof values.id === 'string' ? values.id : leaveEntryIdFor(entry);
				if (context.leave_entries.some((row) => row.id === id)) continue;
				context.leave_entries.push({ ...values, id, approval_id: null } as Row);
				createdEntries.add(id);
			}
		});
	const db = {
		employments: reads('employments'),
		companies: reads('companies'),
		jurisdiction_settings: reads('jurisdiction_settings'),
		employees: reads('employees'),
		employment_terms: reads('employment_terms'),
		employee_children: reads('employee_children'),
		leave_catalogue: reads('leave_catalogue'),
		leave_entitlements: { ...reads('leave_entitlements'), mutate: mutateEntitlements },
		leave_entries: { ...reads('leave_entries'), mutate: mutateEntries },
		leave_requests: { ...reads('leave_requests'), findPending: pending }
	};
	const api = { db: db as unknown as Db } as Api;
	/** One entitlement as its owning employment nests it: new rows whole, stored rows by id plus any change, each with its entries. */
	const nestedEntitlement = (entitlement: Row) => {
		const entries = context.leave_entries
			.filter((entry) => entry.leave_entitlement_id === entitlement.id)
			.map((entry) => (createdEntries.has(entry.id) ? stripSystem(entry) : { id: entry.id }));
		const own = createdEntitlements.has(entitlement.id)
			? stripSystem(entitlement)
			: { id: entitlement.id, ...stripSystem(updatedEntitlements.get(entitlement.id) ?? {}) };
		return { ...own, entry_leave_entitlement: entries };
	};
	return {
		api,
		/** Every entitlement of one employment, the complete set, for `leave_entitlement_employment`. */
		nestedEntitlementsOf: (employmentId: string) =>
			context.leave_entitlements
				.filter((entitlement) => entitlement.employment_id === employmentId)
				.map(nestedEntitlement),
		/** The employments whose nested set changed: one root write each, nothing else touched. */
		changedEmploymentIds: () => {
			const employmentOf = new Map(
				context.leave_entitlements.map((row) => [row.id, String(row.employment_id)])
			);
			const changed = new Set<string>();
			for (const id of createdEntitlements) changed.add(employmentOf.get(id) ?? '');
			for (const id of updatedEntitlements.keys()) changed.add(employmentOf.get(id) ?? '');
			for (const id of createdEntries) {
				const entry = context.leave_entries.find((row) => row.id === id);
				if (entry != null) changed.add(employmentOf.get(String(entry.leave_entitlement_id)) ?? '');
			}
			changed.delete('');
			return [...changed];
		},
		counts: () => ({
			entitlements_created: createdEntitlements.size,
			entitlements_updated: updatedEntitlements.size,
			entries_created: createdEntries.size
		})
	};
};

/** Values as a mutate accepts them: the row without the columns the runtime owns. */
const stripSystem = (row: Record<string, unknown>): Record<string, unknown> => {
	const {
		approval_id: _approval,
		created_at: _created,
		updated_at: _updated,
		row_version: _version,
		sys_period: _period,
		...values
	} = row;
	return values;
};

/**
 * Writes what a planner planned: one nested write per changed employment, on the employment root
 * (`leave_entitlement_employment` → entitlements → `entry_leave_entitlement`), under the formula
 * ids the planner assigned. The complete set is restated, so nothing an employment already had is
 * dropped.
 */
export const applyLeavePlan = (api: Api, planner: ReturnType<typeof leavePlanner>) => {
	const ids = planner.changedEmploymentIds();
	if (ids.length === 0) return Effect.void;
	const employments = api.db as unknown as {
		readonly employments: {
			readonly mutate: (rows: ReadonlyArray<Record<string, unknown>>) => Effect.Effect<void>;
		};
	};
	return employments.employments.mutate(
		ids.map((id) => ({ id, leave_entitlement_employment: planner.nestedEntitlementsOf(id) }))
	);
};
