import { Effect } from 'effect';
import type { AutomationApi } from '@norbital-ai/bolt/authoring';
import type { WorkspaceRow } from '../../collections/leave_requests/$types.js';
import { reconcileEmploymentLeave } from './reconcile.js';

/**
 * Leave entitlements are generated by one service and written inline with the row that owns them.
 *
 * The arithmetic in `reconcile.ts` reads and writes through the authored `api.db` surface. Here it
 * runs against an in-memory context that was read once for a whole batch, and everything it wrote
 * is handed back as nested rows for the caller's own mutation: an employment nests its accounts
 * (each nesting its entitlement entries), a sealed statutory profile nests the adjustments it
 * causes. Nothing here writes to the database. Ids are deterministic, so an account can be
 * referenced by the entries that open it before anything exists, and a leave request can name its
 * account by formula.
 */

/** The leave service needs only the data surface; hooks and automations hand it theirs. */
export type LeaveApi = Readonly<{ readonly db: AutomationApi['db'] }>;
type Api = LeaveApi;
type Row = Readonly<Record<string, unknown>> & { readonly id: string };
type Db = Api['db'];

const LIMIT = 5_000;

export { leaveAccountIdFor, leaveEntryIdFor, requestSourceKey, stableUuid } from './identity.js';
import { leaveAccountIdFor, leaveEntryIdFor } from './identity.js';

type LeaveContext = {
	readonly employments: Row[];
	readonly companies: Row[];
	readonly employees: Row[];
	readonly employment_terms: Row[];
	readonly employee_children: Row[];
	readonly leave_plans: Row[];
	readonly leave_types: Row[];
	readonly jurisdictions: Row[];
	readonly leave_accounts: Row[];
	readonly leave_entries: Row[];
	readonly leave_requests: Row[];
};

const chunks = <T>(items: ReadonlyArray<T>, size: number): T[][] => {
	const out: T[][] = [];
	for (let index = 0; index < items.length; index += size)
		out.push([...items.slice(index, index + size)]);
	return out;
};

const readAll = <T>(
	ids: ReadonlyArray<string>,
	read: (chunk: ReadonlyArray<string>) => Effect.Effect<ReadonlyArray<T>>
): Effect.Effect<T[]> =>
	Effect.map(
		Effect.forEach(chunks([...new Set(ids)], 200), (chunk) => read(chunk), { concurrency: 4 }),
		(pages) => {
			if (pages.some((page) => page.length >= LIMIT))
				throw new Error(
					'Leave context read hit its page ceiling; the batch is too large to plan safely.'
				);
			return pages.flat();
		}
	);

/** Every row the arithmetic may ask for while reconciling these employments, read in bulk. */
export const readLeaveContext = (
	api: Api,
	employmentIds: ReadonlyArray<string>,
	extra: {
		readonly companyIds?: ReadonlyArray<string>;
		readonly employeeIds?: ReadonlyArray<string>;
		/** The planning date; only the leave years around it are read, never the whole history. */
		readonly asOf: string;
	}
) =>
	Effect.gen(function* () {
		// A leave year is labelled by the calendar year it starts in, so the previous, current and
		// next leave years of any company lie within two calendar years of the planning date.
		const yearFloor = Number(extra.asOf.slice(0, 4)) - 2;
		const db = api.db as unknown as Record<
			string,
			{ findMany: (input: Record<string, unknown>) => Effect.Effect<ReadonlyArray<Row>> }
		>;
		const many = (collection: string, where: Record<string, unknown>) =>
			db[collection]!.findMany({ where, limit: LIMIT });
		const employments = yield* readAll(employmentIds, (ids) =>
			many('employments', { id: { in: ids }, approval_id: { isNull: true } })
		);
		const companyIds = [
			...new Set([...employments.map((row) => String(row.company_id)), ...(extra.companyIds ?? [])])
		];
		const employeeIds = [
			...new Set([
				...employments.map((row) => String(row.employee_id)),
				...(extra.employeeIds ?? [])
			])
		];
		const presentIds = employments.map((row) => row.id);
		const [companies, employees, terms, children, plans, accounts, requests] = yield* Effect.all(
			[
				readAll(companyIds, (ids) =>
					many('companies', { id: { in: ids }, approval_id: { isNull: true } })
				),
				readAll(employeeIds, (ids) => many('employees', { id: { in: ids } })),
				readAll(presentIds, (ids) =>
					many('employment_terms', { employment_id: { in: ids }, approval_id: { isNull: true } })
				),
				readAll(presentIds, (ids) =>
					many('employee_children', { employment_id: { in: ids }, approval_id: { isNull: true } })
				),
				readAll(companyIds, (ids) =>
					many('leave_plans', { company_id: { in: ids }, approval_id: { isNull: true } })
				),
				readAll(presentIds, (ids) =>
					many('leave_accounts', {
						employment_id: { in: ids },
						approval_id: { isNull: true },
						OR: [
							{ leave_year: { gte: yearFloor } },
							{ account_kind: { eq: 'EVENT' }, status: { eq: 'OPEN' } }
						]
					})
				),
				readAll(presentIds, (ids) =>
					many('leave_requests', { employment_id: { in: ids }, approval_id: { isNull: true } })
				)
			],
			{ concurrency: 'unbounded' }
		);
		const anchorIds = [...new Set(companies.map((row) => String(row.jurisdiction_id)))];
		const anchors = yield* readAll(anchorIds, (ids) =>
			many('jurisdictions', { id: { in: ids }, approval_id: { isNull: true } })
		);
		const codes = [...new Set(anchors.map((row) => String(row.code)))];
		const jurisdictions = yield* readAll(codes, (ids) =>
			many('jurisdictions', { code: { in: ids }, approval_id: { isNull: true } })
		);
		const planIds = plans.map((row) => row.id);
		const [types, entries] = yield* Effect.all(
			[
				readAll(planIds, (ids) => many('leave_types', { leave_plan_id: { in: ids } })),
				readAll(
					accounts.map((row) => row.id),
					(ids) =>
						many('leave_entries', { leave_account_id: { in: ids }, approval_id: { isNull: true } })
				)
			],
			{ concurrency: 'unbounded' }
		);
		return {
			employments: [...employments],
			companies: [...companies],
			employees: [...employees],
			employment_terms: [...terms],
			employee_children: [...children],
			leave_plans: [...plans],
			leave_types: [...types],
			jurisdictions: [...jurisdictions],
			leave_accounts: [...accounts],
			leave_entries: [...entries],
			leave_requests: [...requests]
		} satisfies LeaveContext;
	});

type Where = Readonly<Record<string, unknown>>;

/** The small `where` vocabulary the leave arithmetic uses, evaluated against a row in memory. */
const matches = (row: Row, where: Where | undefined): boolean => {
	if (where == null) return true;
	return Object.entries(where).every(([field, condition]) => {
		if (field === 'AND') return (condition as Where[]).every((part) => matches(row, part));
		if (field === 'OR') return (condition as Where[]).some((part) => matches(row, part));
		const value = row[field];
		const rule = condition as Readonly<Record<string, unknown>>;
		return Object.entries(rule).every(([operator, expected]) => {
			switch (operator) {
				case 'eq':
					return value === expected;
				case 'ne':
					return value !== expected;
				case 'in':
					return (expected as unknown[]).includes(value);
				case 'isNull':
					return expected ? value == null : value != null;
				case 'isNotNull':
					return expected ? value != null : value == null;
				case 'gt':
					return value != null && (value as string | number) > (expected as string | number);
				case 'gte':
					return value != null && (value as string | number) >= (expected as string | number);
				case 'lt':
					return value != null && (value as string | number) < (expected as string | number);
				case 'lte':
					return value != null && (value as string | number) <= (expected as string | number);
				default:
					throw new Error(`leave batch facade: unsupported where operator ${operator} on ${field}`);
			}
		});
	});
};

const select = (rows: ReadonlyArray<Row>, input: Record<string, unknown> | undefined): Row[] => {
	let out = rows.filter((row) => matches(row, input?.where as Where | undefined));
	const orderBy = input?.orderBy as Record<string, 'asc' | 'desc'> | undefined;
	if (orderBy != null) {
		const [[field, direction]] = Object.entries(orderBy);
		out = [...out].sort((left, right) => {
			const a = left[field] as string | number;
			const b = right[field] as string | number;
			return (a < b ? -1 : a > b ? 1 : 0) * (direction === 'desc' ? -1 : 1);
		});
	}
	const limit = input?.limit as number | undefined;
	return limit == null ? out : out.slice(0, limit);
};

/**
 * The arithmetic's api, backed by the context. Reads see every write made so far; writes are
 * kept in memory under deterministic ids and handed back as nested rows for the owning mutation.
 */
export const leavePlanner = (
	context: LeaveContext,
	pending: Api['db']['leave_requests']['findPending']
) => {
	const createdAccounts = new Set<string>();
	const updatedAccounts = new Map<string, Record<string, unknown>>();
	const createdEntries = new Set<string>();
	const reads = (collection: keyof LeaveContext) => ({
		findMany: (input?: Record<string, unknown>) =>
			Effect.succeed(select(context[collection], input)),
		findFirst: (input?: Record<string, unknown>) =>
			Effect.succeed(select(context[collection], { ...input, limit: 1 })[0] ?? null)
	});
	const mutateAccounts = (rows: ReadonlyArray<Record<string, unknown>>) =>
		Effect.sync(() => {
			for (const values of rows) {
				const id =
					typeof values.id === 'string'
						? values.id
						: leaveAccountIdFor(values as Parameters<typeof leaveAccountIdFor>[0]);
				const existing = context.leave_accounts.find((row) => row.id === id);
				if (existing != null) {
					Object.assign(existing, values, { id });
					if (!createdAccounts.has(id))
						updatedAccounts.set(id, { ...(updatedAccounts.get(id) ?? {}), ...values, id });
				} else {
					context.leave_accounts.push({ ...values, id, approval_id: null } as Row);
					createdAccounts.add(id);
				}
			}
		});
	const mutateEntries = (rows: ReadonlyArray<Record<string, unknown>>) =>
		Effect.sync(() => {
			for (const values of rows) {
				const entry = values as { leave_account_id: string; source_key: string };
				const id = typeof values.id === 'string' ? values.id : leaveEntryIdFor(entry);
				if (context.leave_entries.some((row) => row.id === id)) continue;
				context.leave_entries.push({ ...values, id, approval_id: null } as Row);
				createdEntries.add(id);
			}
		});
	const refuseWrite = (collection: string) => () =>
		Effect.die(new Error(`the leave planner never writes ${collection}; it only plans`));
	const db = {
		employments: reads('employments'),
		companies: reads('companies'),
		employees: reads('employees'),
		employment_terms: reads('employment_terms'),
		employee_children: reads('employee_children'),
		leave_plans: { ...reads('leave_plans'), mutate: refuseWrite('leave_plans') },
		leave_types: reads('leave_types'),
		jurisdictions: reads('jurisdictions'),
		leave_accounts: { ...reads('leave_accounts'), mutate: mutateAccounts },
		leave_entries: { ...reads('leave_entries'), mutate: mutateEntries },
		leave_requests: { ...reads('leave_requests'), findPending: pending }
	};
	const api = { db: db as unknown as Db } as Api;
	/** One account as its owning employment nests it: new rows whole, stored rows by id plus any change, each with its entries. */
	const nestedAccount = (account: Row) => {
		const entries = context.leave_entries
			.filter((entry) => entry.leave_account_id === account.id)
			.map((entry) => (createdEntries.has(entry.id) ? stripSystem(entry) : { id: entry.id }));
		const own = createdAccounts.has(account.id)
			? stripSystem(account)
			: { id: account.id, ...stripSystem(updatedAccounts.get(account.id) ?? {}) };
		return { ...own, entry_leave_account: entries };
	};
	return {
		api,
		/** Every account of one employment, the complete set, for `leave_account_employment`. */
		nestedAccountsOf: (employmentId: string) =>
			context.leave_accounts
				.filter((account) => account.employment_id === employmentId)
				.map(nestedAccount),
		/** The employments whose nested account set changed: one root write each, nothing else touched. */
		changedEmploymentIds: () => {
			const accountEmployment = new Map(
				context.leave_accounts.map((account) => [account.id, String(account.employment_id)])
			);
			const changed = new Set<string>();
			for (const id of createdAccounts) changed.add(accountEmployment.get(id) ?? '');
			for (const id of updatedAccounts.keys()) changed.add(accountEmployment.get(id) ?? '');
			for (const id of createdEntries) {
				const entry = context.leave_entries.find((row) => row.id === id);
				if (entry != null) changed.add(accountEmployment.get(String(entry.leave_account_id)) ?? '');
			}
			changed.delete('');
			return [...changed];
		},
		counts: () => ({
			accounts_created: createdAccounts.size,
			accounts_updated: updatedAccounts.size,
			entries_created: createdEntries.size
		})
	};
};

/** Values as a mutate accepts them: the row without the columns the runtime owns. */
const stripSystem = (row: Record<string, unknown>): Record<string, unknown> => {
	const {
		approval_id: _approval,
		created_at: _created,
		updated_at: _updated,
		row_version: _version,
		sys_period: _period,
		...values
	} = row;
	return values;
};

/**
 * Writes what a planner planned: one nested write per changed employment, on the employment root
 * (`leave_account_employment` → accounts → `entry_leave_account`), under the formula ids the planner
 * assigned. The complete set is restated, so nothing an employment already had is dropped.
 */
export const applyLeavePlan = (api: Api, planner: ReturnType<typeof leavePlanner>) => {
	const ids = planner.changedEmploymentIds();
	if (ids.length === 0) return Effect.void;
	const employments = api.db as unknown as {
		readonly employments: {
			readonly mutate: (rows: ReadonlyArray<Record<string, unknown>>) => Effect.Effect<void>;
		};
	};
	return employments.employments.mutate(
		ids.map((id) => ({ id, leave_account_employment: planner.nestedAccountsOf(id) }))
	);
};
