<script lang="ts">
	/**
	 * One settled thing a payslip did about one input, read only.
	 *
	 * Nothing writes here by hand — the payroll engine writes every adjustment when the run is built
	 * — so this panel explains a figure rather than offering to change one.
	 *
	 * `input` is the one discriminated reference handle over the four captured-input junctions; its
	 * physical per-arm UUID columns are generated by Bolt and never appear in this form. Every row
	 * names exactly one capture, and the exclusive arc the database enforces is what makes the
	 * provenance single-causal.
	 *
	 * The settled `label` is what the row paid under, and `statutory_rule_key` — work-day rows only
	 * — names the rule that priced it inside the run's statutory snapshot.
	 */
	import { client } from '../../lib/workspace-client.js';
	import { useI18n } from '@norbital-ai/ui/i18n';
	import type { TenantI18nKeys } from '$bolt/i18n-keys';
	import type { RepresentationProps } from './$types.js';
	import { CollectionForm } from '@norbital-ai/ui/collection-form';
	import { Column, Grid } from '@norbital-ai/ui/layout';

	let { record }: RepresentationProps = $props();
	const { t } = useI18n<TenantI18nKeys>();
</script>

{#if record}
	<CollectionForm {client} collection="payslip_adjustments" defaultValues={record} disabled>
		{#snippet children({ Field })}
			<Grid gap="md" minimum="panel">
				<Field
					name="payslip_id"
					label={t('component.payslip')}
					relationOptions={{
						label: (payslip) =>
							[payslip.currency, payslip.net]
								.filter((part) => part != null && part !== '')
								.join(' ') || '—',
						limit: 500
					}}
				/>
				<Field name="period" label={t('component.pay_period')} />
				<Field name="sequence" label={t('component.applied_at')} />
				<Field name="bucket" label={t('component.bucket')} />
				<Field name="amount" label={t('component.amount')} />
				<Field name="quantity" label={t('component.quantity')} />
				<Field name="rate" label={t('component.rate')} />
				<Field name="label" label={t('component.component')} />
				<Column span="all">
					<Field name="statutory_rule_key" label={t('component.statutory_rule_key')} />
				</Column>
				<Column span="all"><Field name="input" label={t('component.input_type')} /></Column>
			</Grid>
		{/snippet}
	</CollectionForm>
{:else}
	<p class="text-sm text-muted-foreground">
		A payslip adjustment is written by the payroll engine, never by hand: build the payroll run and
		it writes one row per input it took into account.
	</p>
{/if}
