/**
 * The kiosk's voice: pre-generated clips, one at a time, and nothing else.
 *
 * Every phrase the kiosk says is a clip under `kiosk-voice/<language>/<key>.<format>`, generated by
 * `scripts/generate-kiosk-voice.mjs` from `phrases.ts` and shipped beside the face models by the
 * `kiosk-voice-clips` plugin in `vite.config.ts`. The narrator plays them through an `Audio`
 * element with a small queue: a phrase that arrives while one is playing waits for it, and nothing
 * ever talks over anything. There is no browser or system voice: a clip the release does not
 * carry is silence, logged once, and the build refuses to ship a phrase without one.
 */
import { KIOSK_VOICE_BASE } from './config.js';
import {
	KIOSK_VOICE_CLIP_FORMAT,
	type KioskPhraseKey,
	type KioskVoiceLanguage
} from './phrases.js';

/** Where one phrase's clip lives, resolved beside this chunk the way the face models are. */
const kioskClipUrl = (
	language: KioskVoiceLanguage,
	key: KioskPhraseKey,
	base: string = KIOSK_VOICE_BASE
): string => new URL(`${language}/${key}.${KIOSK_VOICE_CLIP_FORMAT}`, base).href;

/** How one clip playback ended. `missing` marks the URL so it is never fetched again. */
type KioskClipOutcome = 'played' | 'missing' | 'stopped';

type KioskClipPlayback = Readonly<{
	done: Promise<KioskClipOutcome>;
	stop: () => void;
}>;

/**
 * What the narrator needs from the platform. Injected so the queue runs under Node in tests with
 * a scripted player, and so the browser wiring below stays a few lines.
 */
type KioskNarratorPlatform = Readonly<{
	/** Starts one clip; `done` settles when it ends, cannot load, or is stopped. */
	play: (url: string) => KioskClipPlayback;
	/** Browser speech for a phrase whose clip is missing; settles when the utterance ends. */
}>;

type KioskNarrator = Readonly<{
	/** Queues one phrase in the current language; a no-op while the voice is off. */
	say: (key: KioskPhraseKey) => void;
	/** Drops every queued phrase and silences the one playing. */
	stop: () => void;
	setLanguage: (language: KioskVoiceLanguage) => void;
	setEnabled: (enabled: boolean) => void;
	/** Clip URLs the platform reported missing; the fallback spoke them instead. */
	readonly missing: ReadonlySet<string>;
}>;

/** A phrase that arrives when this many are already waiting evicts the oldest waiting one. */
const KIOSK_NARRATOR_MAX_PENDING = 2;

export const createKioskNarrator = (
	platform: KioskNarratorPlatform,
	options: Readonly<{ language: KioskVoiceLanguage; enabled?: boolean }>
): KioskNarrator => {
	let language = options.language;
	let enabled = options.enabled ?? true;
	const missing = new Set<string>();
	const pending: Array<{ key: KioskPhraseKey; language: KioskVoiceLanguage }> = [];
	let current: { key: KioskPhraseKey; playback: KioskClipPlayback | null } | null = null;
	/** Bumped by `stop`, so a drain loop that was awaiting a clip exits instead of continuing. */
	let generation = 0;

	const drain = async (myGeneration: number): Promise<void> => {
		while (myGeneration === generation) {
			const next = pending.shift();
			if (next === undefined) {
				current = null;
				return;
			}
			const url = kioskClipUrl(next.language, next.key);
			// A phrase with no clip is silent. There is no browser-speech fallback: the system voice
			// is the sound the owner asked never to hear again, and every listed phrase ships a clip.
			if (missing.has(url)) continue;
			const playback = platform.play(url);
			current = { key: next.key, playback };
			const outcome = await playback.done;
			if (outcome === 'missing') {
				missing.add(url);
				console.warn(`[kiosk] no voice clip for ${next.language}/${next.key}`);
			}
		}
	};

	const stop = () => {
		generation += 1;
		pending.length = 0;
		current?.playback?.stop();
		current = null;
	};

	return {
		say: (key) => {
			if (!enabled) return;
			// The same phrase twice in a row is one phrase: the loop re-reports a hint every tick.
			const tail = pending.at(-1)?.key ?? current?.key;
			if (tail === key) return;
			if (pending.length >= KIOSK_NARRATOR_MAX_PENDING) pending.shift();
			pending.push({ key, language });
			if (current === null) void drain(generation);
		},
		stop,
		setLanguage: (next) => {
			language = next;
		},
		setEnabled: (next) => {
			enabled = next;
			if (!next) stop();
		},
		missing
	};
};

/**
 * The browser platform: one `Audio` per clip.
 *
 * A clip the server answers with a 404 fires `error` on the element (the request is made only when
 * playback starts, so a missing clip costs one failed fetch, once). A `play()` refused by the
 * autoplay policy is `stopped`, not `missing`: the clip exists, the page has just not been touched
 * yet, and marking it missing would silence a clip that exists.
 */
export const browserNarratorPlatform = (): KioskNarratorPlatform => ({
	play: (url) => {
		const audio = new Audio(url);
		audio.preload = 'auto';
		let settle: (outcome: KioskClipOutcome) => void = () => {};
		const done = new Promise<KioskClipOutcome>((resolve) => {
			settle = resolve;
		});
		audio.addEventListener('ended', () => settle('played'), { once: true });
		audio.addEventListener('error', () => settle('missing'), { once: true });
		audio.play().catch((failure: unknown) => {
			settle(
				failure instanceof DOMException && failure.name === 'NotAllowedError'
					? 'stopped'
					: 'missing'
			);
		});
		return {
			done,
			stop: () => {
				audio.pause();
				settle('stopped');
			}
		};
	}
});
