/**
 * The kiosk's voice: pre-generated clips, one at a time, with browser speech only as a fallback.
 *
 * Every phrase the kiosk says is a clip under `kiosk-voice/<language>/<key>.<format>`, generated by
 * `scripts/generate-kiosk-voice.mjs` from `phrases.ts` and shipped beside the face models by the
 * `kiosk-voice-clips` plugin in `vite.config.ts`. The narrator plays them through an `Audio`
 * element with a small queue: a phrase that arrives while one is playing waits for it, and nothing
 * ever talks over anything. A clip the release does not carry (a phrase added after the last
 * generation) is spoken by the browser with the same text, when it has a natural local voice.
 */
import { KIOSK_VOICE_BASE } from './config.js';
import {
	KIOSK_VOICE_CLIP_FORMAT,
	kioskPhraseText,
	type KioskPhraseKey,
	type KioskVoiceLanguage
} from './phrases.js';

/** Where one phrase's clip lives, resolved beside this chunk the way the face models are. */
const kioskClipUrl = (
	language: KioskVoiceLanguage,
	key: KioskPhraseKey,
	base: string = KIOSK_VOICE_BASE
): string => new URL(`${language}/${key}.${KIOSK_VOICE_CLIP_FORMAT}`, base).href;

/** How one clip playback ended. `missing` marks the URL so it is never fetched again. */
type KioskClipOutcome = 'played' | 'missing' | 'stopped';

type KioskClipPlayback = Readonly<{
	done: Promise<KioskClipOutcome>;
	stop: () => void;
}>;

/**
 * What the narrator needs from the platform. Injected so the queue runs under Node in tests with
 * a scripted player, and so the browser wiring below stays a few lines.
 */
type KioskNarratorPlatform = Readonly<{
	/** Starts one clip; `done` settles when it ends, cannot load, or is stopped. */
	play: (url: string) => KioskClipPlayback;
	/** Browser speech for a phrase whose clip is missing; settles when the utterance ends. */
	speak: (text: string, language: KioskVoiceLanguage) => Promise<void>;
}>;

type KioskNarrator = Readonly<{
	/** Queues one phrase in the current language; a no-op while the voice is off. */
	say: (key: KioskPhraseKey) => void;
	/** Drops every queued phrase and silences the one playing. */
	stop: () => void;
	setLanguage: (language: KioskVoiceLanguage) => void;
	setEnabled: (enabled: boolean) => void;
	/** Clip URLs the platform reported missing; the fallback spoke them instead. */
	readonly missing: ReadonlySet<string>;
}>;

/** A phrase that arrives when this many are already waiting evicts the oldest waiting one. */
const KIOSK_NARRATOR_MAX_PENDING = 2;

export const createKioskNarrator = (
	platform: KioskNarratorPlatform,
	options: Readonly<{ language: KioskVoiceLanguage; enabled?: boolean }>
): KioskNarrator => {
	let language = options.language;
	let enabled = options.enabled ?? true;
	const missing = new Set<string>();
	const pending: Array<{ key: KioskPhraseKey; language: KioskVoiceLanguage }> = [];
	let current: { key: KioskPhraseKey; playback: KioskClipPlayback | null } | null = null;
	/** Bumped by `stop`, so a drain loop that was awaiting a clip exits instead of continuing. */
	let generation = 0;

	const drain = async (myGeneration: number): Promise<void> => {
		while (myGeneration === generation) {
			const next = pending.shift();
			if (next === undefined) {
				current = null;
				return;
			}
			const url = kioskClipUrl(next.language, next.key);
			if (missing.has(url)) {
				current = { key: next.key, playback: null };
				await platform.speak(kioskPhraseText(next.key, next.language), next.language);
				continue;
			}
			const playback = platform.play(url);
			current = { key: next.key, playback };
			const outcome = await playback.done;
			if (outcome === 'missing') {
				missing.add(url);
				if (myGeneration !== generation) return;
				current = { key: next.key, playback: null };
				await platform.speak(kioskPhraseText(next.key, next.language), next.language);
			}
		}
	};

	const stop = () => {
		generation += 1;
		pending.length = 0;
		current?.playback?.stop();
		current = null;
	};

	return {
		say: (key) => {
			if (!enabled) return;
			// The same phrase twice in a row is one phrase: the loop re-reports a hint every tick.
			const tail = pending.at(-1)?.key ?? current?.key;
			if (tail === key) return;
			if (pending.length >= KIOSK_NARRATOR_MAX_PENDING) pending.shift();
			pending.push({ key, language });
			if (current === null) void drain(generation);
		},
		stop,
		setLanguage: (next) => {
			language = next;
		},
		setEnabled: (next) => {
			enabled = next;
			if (!next) stop();
		},
		missing
	};
};

/**
 * The browser platform: one `Audio` per clip, `speechSynthesis` for the fallback.
 *
 * A clip the server answers with a 404 fires `error` on the element (the request is made only when
 * playback starts, so a missing clip costs one failed fetch, once). A `play()` refused by the
 * autoplay policy is `stopped`, not `missing`: the clip exists, the page has just not been touched
 * yet, and marking it missing would make the fallback speak it, which the same policy refuses.
 */
export const browserNarratorPlatform = (
	voice: () => SpeechSynthesisVoice | null
): KioskNarratorPlatform => ({
	play: (url) => {
		const audio = new Audio(url);
		audio.preload = 'auto';
		let settle: (outcome: KioskClipOutcome) => void = () => {};
		const done = new Promise<KioskClipOutcome>((resolve) => {
			settle = resolve;
		});
		audio.addEventListener('ended', () => settle('played'), { once: true });
		audio.addEventListener('error', () => settle('missing'), { once: true });
		audio.play().catch((failure: unknown) => {
			settle(
				failure instanceof DOMException && failure.name === 'NotAllowedError'
					? 'stopped'
					: 'missing'
			);
		});
		return {
			done,
			stop: () => {
				audio.pause();
				settle('stopped');
			}
		};
	},
	speak: (text, language) =>
		new Promise((resolve) => {
			const picked = voice();
			if (picked === null || !('speechSynthesis' in window)) {
				resolve();
				return;
			}
			const utterance = new SpeechSynthesisUtterance(text);
			utterance.voice = picked;
			utterance.lang = picked.lang || language;
			utterance.addEventListener('end', () => resolve(), { once: true });
			utterance.addEventListener('error', () => resolve(), { once: true });
			window.speechSynthesis.speak(utterance);
		})
});

/**
 * Which browser voice the fallback may use.
 *
 * A `SpeechSynthesisUtterance` with no `voice` gets the browser default, which on Firefox and most
 * Chromium builds is the low-quality system voice. The pick is a voice that runs on the device
 * (`localService`: no network round trip while a person waits), speaks the kiosk's locale, and
 * whose name the vendor marks as one of the natural ones. No such voice means a missing clip is
 * silent rather than spoken badly.
 */
export type KioskVoice = Pick<
	SpeechSynthesisVoice,
	'name' | 'lang' | 'localService' | 'voiceURI' | 'default'
>;

/** Name fragments the vendors use for their natural voices, on macOS, iOS, Android and Chrome. */
const NATURAL_VOICE_MARKS: readonly string[] = [
	'enhanced',
	'premium',
	'natural',
	'google',
	'samantha',
	'daniel',
	'tingting',
	'ting-ting',
	'meijia'
];

const languageOf = (tag: string): string => tag.toLowerCase().replace('_', '-').split('-')[0] ?? '';

const normalize = (tag: string): string => tag.toLowerCase().replace('_', '-');

/** True when the voice runs locally, speaks the locale's language and carries a natural mark. */
export const isAcceptableKioskVoice = (voice: KioskVoice, locale: string): boolean =>
	voice.localService &&
	languageOf(voice.lang) === languageOf(locale) &&
	NATURAL_VOICE_MARKS.some((mark) => voice.name.toLowerCase().includes(mark));

/**
 * The voice to speak with: the stored pick when it is still installed and still acceptable, else
 * the best acceptable voice (an exact locale match first, then the platform default), else null.
 */
export const pickKioskVoice = <Voice extends KioskVoice>(
	voices: readonly Voice[],
	locale: string,
	storedUri: string | null
): Voice | null => {
	const stored = storedUri === null ? undefined : voices.find((v) => v.voiceURI === storedUri);
	if (stored !== undefined && isAcceptableKioskVoice(stored, locale)) return stored;
	const wanted = normalize(locale);
	const rank = (voice: Voice): number =>
		(normalize(voice.lang) === wanted ? 0 : 2) + (voice.default ? 0 : 1);
	const candidates = voices
		.filter((voice) => isAcceptableKioskVoice(voice, locale))
		.toSorted((left, right) => rank(left) - rank(right));
	return candidates[0] ?? null;
};
