<script lang="ts">
	/**
	 * One settled thing a payslip did about one input, read only.
	 *
	 * Nothing writes here by hand — the payroll engine writes every adjustment when the run is built
	 * — so this panel explains a figure rather than offering to change one.
	 *
	 * `source` is the one discriminated reference handle; its physical per-arm UUID columns are
	 * generated by Bolt and never appear in this form. Its three predecessors — `component_entry_id`,
	 * `statutory_contribution_id`, `repayment_agreement_id` — were `generatedAlwaysAs` projections of
	 * a union in jsonb, offered by the auto form as editable uuids the database would have refused.
	 *
	 * A zero amount is not an empty row: it says the run read this source and priced it at nothing,
	 * and the row still holds the settlement claim that stops the source being edited or deleted.
	 */
	import { client } from '../../lib/workspace-client.js';
	import { useI18n } from '@norbital-ai/ui/i18n';
	import type { TenantI18nKeys } from '$bolt/i18n-keys';
	import type { RepresentationProps } from './$types.js';
	import { CollectionForm } from '@norbital-ai/ui/collection-form';
	import { Column, Grid } from '@norbital-ai/ui/layout';

	let { record }: RepresentationProps = $props();
	const { t } = useI18n<TenantI18nKeys>();
</script>

{#if record}
	<CollectionForm {client} collection="payslip_adjustments" defaultValues={record} disabled>
		{#snippet children({ Field })}
			<Grid gap="md" minimum="panel">
				<Field
					name="payslip_id"
					label={t('component.payslip')}
					relationOptions={{
						label: (payslip) =>
							[payslip.currency, payslip.net]
								.filter((part) => part != null && part !== '')
								.join(' ') || '—',
						limit: 500
					}}
				/>
				<Field name="period" label={t('component.pay_period')} />
				<Field name="sequence" label={t('component.applied_at')} />
				<Field name="bucket" label={t('component.bucket')} />
				<Field name="amount" label={t('component.amount')} />
				<Field name="quantity" label={t('component.quantity')} />
				<Field name="rate" label={t('component.rate')} />
				<Field
					name="pay_component_id"
					label={t('component.pay_component')}
					relationOptions={{
						label: (component: { readonly code?: unknown }) =>
							component.code != null && component.code !== '' ? String(component.code) : '—',
						orderBy: { code: 'asc' },
						limit: 500
					}}
				/>
				<Column span="all">
					<Field name="overtime_band" label={t('component.overtime_band')} />
				</Column>
				<Column span="all"><Field name="source" label={t('component.source_record')} /></Column>
			</Grid>
		{/snippet}
	</CollectionForm>
{:else}
	<p class="text-sm text-muted-foreground">
		A payslip adjustment is written by the payroll engine, never by hand: build the payroll run and
		it writes one row per input it took into account.
	</p>
{/if}
